[profile.dev]
solc = "0.8.20"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true

[programs.devnet]
vibedump = "ViBeDuMp111111111111111111111111111111111"

[programs.mainnet-beta]
vibedump = "ViBeDuMp111111111111111111111111111111111"

[registry]
url = "https://api.github.com/repos/coral-xyz/anchor"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha --require ts-node/register tests/**/*.ts"
